### PR TITLE
Fix #926: Add color resource parameters

### LINKED ISSUE #926: Changing light/dark mode not works for color resources
**AppIntro Version**: current master (SNAPSHOT)

**Device/Android Version**: Emulator / Android 11 (API level 30)

**Issue details / Repro steps / Use case background**: 
If the intro is open and the dark mode configuration changes not all colors are changed.
1. Open intro in light mode
2. Change theme to dark mode by control center

The drawables (set by resource ID) will be changed like expected. All background & font colors (that set directly) does not change.

After the design mode changed the activity will recreated. The slides will added again with new (dark mode) parameters. The colors are set directly and I found that the onActivityCreated [AppIntroBaseFragment.kt#L73](https://github.com/AppIntro/AppIntro/blob/master/appintro/src/main/java/com/github/appintro/AppIntroBaseFragment.kt#L73) method is called while recreating with the "old" parameters and the explicit set colors will be reused.

The simplest solution is to give a color resource ID instead of the color itself. As more cleaner solution we should improve the instance saving flow to keep them per fragment itself instead to referencing to the activity lifecycle.

**Your Code**: 
```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    // Have default + night variants
    // Works fine
    setIndicatorColor(
            selectedIndicatorColor = ContextCompat.getColor(this, R.color.intro_pagination_indicator),
            unselectedIndicatorColor = ContextCompat.getColor(this, R.color.meta_grey)
    )

    // Have default + night variants
    // Works fine
    setBackArrowColor(ContextCompat.getColor(this, R.color.accent))
    setNextArrowColor(ContextCompat.getColor(this, R.color.accent))
    setColorDoneText(ContextCompat.getColor(this, R.color.paper))

    addSlide(AppIntroFragment.newInstance(
            // ...

            // Has default + night variant
            // Works fine
            imageDrawable = R.drawable.ic_logo, 

            // Has default + night variant
            // Does NOT work
            titleColor = ContextCompat.getColor(this, R.color.text),

            // Has default + night variant
            // Does NOT work
            descriptionColor = ContextCompat.getColor(this, R.color.text),

            // Has default + night variant
            // Does NOT work
            backgroundColor = ContextCompat.getColor(this, R.color.paper),
            
            // ...
    ))
}
```

Working light:

Failed dark:

Expected result:

I will playing around a little bit and make a PR next days.

### PR DESCRIPTION
**Pull request by Fabi755**
Fixing #926. As discussed in #948 this PR is re-created for a cleaner state.

### CODE REVIEW

**Review by paolorotolo — COMMENTED** [review]
Sorry for writing this only now.
The code looks fine for me, but I'm just unsure about the naming of the new method `newInstanceWithRes`. 

It's possible to invoke that method passing the `title` and `description` and leaving the default values of the other parameters.
```
        addSlide(AppIntroFragment.newInstanceWithRes(
                "Welcome!",
                "This is a demo of the AppIntro library, with a custom background on each slide!",
        ))
```
In that case, I think that the naming `newInstaceWithRes` would be misleading, because the user expects that a resource is required by the method.

Since this will be the default method to generate instance of AppIntroFragment, I think we should find something more neutral in that sense.

**Comment by cortinico** [comment]
> In that case, I think that the naming `newInstaceWithRes` would be misleading, because the user expects that a resource is required by the method.
> 
> Since this will be the default method to generate instance of AppIntroFragment, I think we should find something more neutral in that sense.

How do we feel about `createInstance()`?

**Comment by paolorotolo** [comment]
Yes, sounds good for me 👍🏻

**Comment by paolorotolo** [comment]
> How do we feel about `createInstance()`?

Yes, sounds good to me! Could you please refactor that?

**Comment by Fabi755** [comment]
So I do the following points:

- [ ] rename `newInstaceWithRes` to `createInstance`
- [ ] solve conflict

Is there something more?

File: appintro/src/main/java/com/github/appintro/AppIntroFragment.kt [hunk 1]
```diff
@@ -32,6 +33,15 @@ class AppIntroFragment : AppIntroBaseFragment() {
          */
         @JvmOverloads
         @JvmStatic
+        @Deprecated(
+            "`newInstance` is deprecated to support color resources with configuration " +
```
Comment (cortinico) [inline appintro/src/main/java/com/github/appintro/AppIntroFragment.kt:37]:
```suggestion
            "`newInstance` is deprecated to support color resources instead of color int for configuration changes and dark theme support "
```

Let's try to be a bit more informative

**Comment by cortinico** [comment]
> Is there something more?

Left a minor comment but otherwise looks great to me 👍

**Review by cortinico — APPROVED** [review]

**Comment by paolorotolo** [comment]
Thanks!
